-- BgLib: Full database install
-- Generated by scripts/build-install-sql.sh — run once in Supabase SQL Editor
-- After running, enable Realtime replication (see supabase/README.md)

-- BgLib: Board Game Library Schema
-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard)

-- Profiles (extends auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  display_name text not null,
  avatar_url text,
  bio text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- Board games catalogue
create table public.games (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  description text,
  min_players integer default 1,
  max_players integer,
  play_time_minutes integer,
  image_url text,
  bgg_id integer,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- Ownership: who owns which games
create table public.ownership (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  game_id uuid references public.games(id) on delete cascade not null,
  condition text default 'good' check (condition in ('new', 'like_new', 'good', 'fair', 'poor')),
  notes text,
  acquired_date date,
  created_at timestamptz default now() not null,
  unique (user_id, game_id)
);

-- Indexes
create index games_title_idx on public.games using gin (to_tsvector('english', title));
create index ownership_user_idx on public.ownership (user_id);
create index ownership_game_idx on public.ownership (game_id);

-- Auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1))
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Updated_at trigger
create or replace function public.update_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger profiles_updated_at before update on public.profiles
  for each row execute function public.update_updated_at();

create trigger games_updated_at before update on public.games
  for each row execute function public.update_updated_at();

-- Row Level Security
alter table public.profiles enable row level security;
alter table public.games enable row level security;
alter table public.ownership enable row level security;

-- Profiles: anyone can read, users can update own
create policy "Profiles are viewable by everyone"
  on public.profiles for select using (true);

create policy "Users can update own profile"
  on public.profiles for update using (auth.uid() = id);

create policy "Users can insert own profile"
  on public.profiles for insert with check (auth.uid() = id);

-- Games: anyone can read, authenticated users can create
create policy "Games are viewable by everyone"
  on public.games for select using (true);

create policy "Authenticated users can create games"
  on public.games for insert with check (auth.uid() is not null);

create policy "Creators can update their games"
  on public.games for update using (auth.uid() = created_by);

-- Ownership: anyone can read, users manage their own
create policy "Ownership is viewable by everyone"
  on public.ownership for select using (true);

create policy "Users can add to their collection"
  on public.ownership for insert with check (auth.uid() = user_id);

create policy "Users can update their ownership"
  on public.ownership for update using (auth.uid() = user_id);

create policy "Users can remove from their collection"
  on public.ownership for delete using (auth.uid() = user_id);

-- View: games with owner count
create or replace view public.games_with_owners as
select
  g.*,
  coalesce(json_agg(
    json_build_object(
      'user_id', p.id,
      'display_name', p.display_name,
      'avatar_url', p.avatar_url,
      'condition', o.condition,
      'notes', o.notes,
      'acquired_date', o.acquired_date
    )
  ) filter (where p.id is not null), '[]') as owners
from public.games g
left join public.ownership o on o.game_id = g.id
left join public.profiles p on p.id = o.user_id
group by g.id;

-- >>> 002_extensions.sql
-- BgLib Extensions Migration
-- Run this in Supabase SQL Editor after the base schema

-- Game nights
create table if not exists public.game_nights (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  description text,
  host_id uuid references public.profiles(id) on delete cascade not null,
  scheduled_at timestamptz not null,
  location text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists public.game_night_games (
  id uuid default gen_random_uuid() primary key,
  game_night_id uuid references public.game_nights(id) on delete cascade not null,
  game_id uuid references public.games(id) on delete cascade not null,
  unique (game_night_id, game_id)
);

create table if not exists public.game_night_rsvps (
  id uuid default gen_random_uuid() primary key,
  game_night_id uuid references public.game_nights(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  status text not null check (status in ('going', 'maybe', 'declined')),
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  unique (game_night_id, user_id)
);

-- Lending / borrowing
create table if not exists public.loans (
  id uuid default gen_random_uuid() primary key,
  game_id uuid references public.games(id) on delete cascade not null,
  lender_id uuid references public.profiles(id) on delete cascade not null,
  borrower_id uuid references public.profiles(id) on delete cascade not null,
  status text not null default 'pending' check (status in ('pending', 'active', 'returned', 'declined', 'cancelled')),
  due_date date,
  notes text,
  borrowed_at timestamptz,
  returned_at timestamptz,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  check (lender_id != borrower_id)
);

-- Web push subscriptions
create table if not exists public.push_subscriptions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  created_at timestamptz default now() not null,
  unique (user_id, endpoint)
);

create index if not exists game_nights_scheduled_idx on public.game_nights (scheduled_at);
create index if not exists loans_lender_idx on public.loans (lender_id);
create index if not exists loans_borrower_idx on public.loans (borrower_id);
create index if not exists loans_status_idx on public.loans (status);

-- Updated_at triggers
create trigger game_nights_updated_at before update on public.game_nights
  for each row execute function public.update_updated_at();

create trigger game_night_rsvps_updated_at before update on public.game_night_rsvps
  for each row execute function public.update_updated_at();

create trigger loans_updated_at before update on public.loans
  for each row execute function public.update_updated_at();

-- RLS
alter table public.game_nights enable row level security;
alter table public.game_night_games enable row level security;
alter table public.game_night_rsvps enable row level security;
alter table public.loans enable row level security;
alter table public.push_subscriptions enable row level security;

-- Game nights policies
create policy "Game nights are viewable by everyone"
  on public.game_nights for select using (true);

create policy "Authenticated users can create game nights"
  on public.game_nights for insert with check (auth.uid() = host_id);

create policy "Hosts can update their game nights"
  on public.game_nights for update using (auth.uid() = host_id);

create policy "Hosts can delete their game nights"
  on public.game_nights for delete using (auth.uid() = host_id);

-- Game night games policies
create policy "Game night games are viewable by everyone"
  on public.game_night_games for select using (true);

create policy "Hosts can manage game night games"
  on public.game_night_games for all using (
    exists (
      select 1 from public.game_nights gn
      where gn.id = game_night_id and gn.host_id = auth.uid()
    )
  );

-- RSVP policies
create policy "RSVPs are viewable by everyone"
  on public.game_night_rsvps for select using (true);

create policy "Users can manage their RSVPs"
  on public.game_night_rsvps for all using (auth.uid() = user_id);

-- Loan policies
create policy "Loans are viewable by involved parties"
  on public.loans for select using (
    auth.uid() = lender_id or auth.uid() = borrower_id
  );

create policy "Borrowers can request loans"
  on public.loans for insert with check (
    auth.uid() = borrower_id and status = 'pending'
  );

create policy "Involved parties can update loans"
  on public.loans for update using (
    auth.uid() = lender_id or auth.uid() = borrower_id
  );

-- Push subscription policies
create policy "Users can view own subscriptions"
  on public.push_subscriptions for select using (auth.uid() = user_id);

create policy "Users can manage own subscriptions"
  on public.push_subscriptions for all using (auth.uid() = user_id);

-- >>> 003_priority_features.sql
-- BgLib Priority Features Migration
-- Run after schema.sql and 002_extensions.sql

-- Groups
create table if not exists public.groups (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  description text,
  invite_code text unique not null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz default now() not null
);

create table if not exists public.group_members (
  id uuid default gen_random_uuid() primary key,
  group_id uuid references public.groups(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  role text not null default 'member' check (role in ('owner', 'admin', 'member')),
  joined_at timestamptz default now() not null,
  unique (group_id, user_id)
);

-- Profile extensions
alter table public.profiles
  add column if not exists onboarding_completed boolean default false not null,
  add column if not exists active_group_id uuid references public.groups(id) on delete set null;

-- Group scoping
alter table public.games
  add column if not exists group_id uuid references public.groups(id) on delete cascade;

alter table public.game_nights
  add column if not exists group_id uuid references public.groups(id) on delete cascade,
  add column if not exists cancelled_at timestamptz;

-- Play logging
create table if not exists public.plays (
  id uuid default gen_random_uuid() primary key,
  group_id uuid references public.groups(id) on delete cascade not null,
  game_id uuid references public.games(id) on delete cascade not null,
  played_at timestamptz default now() not null,
  duration_minutes integer,
  notes text,
  logged_by uuid references public.profiles(id) on delete set null not null,
  created_at timestamptz default now() not null
);

create table if not exists public.play_participants (
  id uuid default gen_random_uuid() primary key,
  play_id uuid references public.plays(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  unique (play_id, user_id)
);

create index if not exists games_group_idx on public.games (group_id);
create index if not exists games_bgg_idx on public.games (bgg_id) where bgg_id is not null;
create index if not exists game_nights_group_idx on public.game_nights (group_id);
create index if not exists plays_group_idx on public.plays (group_id);
create index if not exists plays_game_idx on public.plays (game_id);
create index if not exists group_members_user_idx on public.group_members (user_id);

-- Updated signup: create default group
create or replace function public.handle_new_user()
returns trigger as $$
declare
  new_group_id uuid;
  display text;
  code text;
begin
  display := coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1));
  code := upper(substring(replace(gen_random_uuid()::text, '-', '') from 1 for 8));

  insert into public.profiles (id, display_name)
  values (new.id, display);

  insert into public.groups (name, invite_code, created_by)
  values (display || '''s Library', code, new.id)
  returning id into new_group_id;

  insert into public.group_members (group_id, user_id, role)
  values (new_group_id, new.id, 'owner');

  update public.profiles
  set active_group_id = new_group_id
  where id = new.id;

  return new;
end;
$$ language plpgsql security definer;

-- Backfill groups for existing users
do $$
declare
  p record;
  gid uuid;
  code text;
begin
  for p in select id, display_name from public.profiles loop
    if not exists (select 1 from public.group_members where user_id = p.id) then
      code := upper(substring(replace(gen_random_uuid()::text, '-', '') from 1 for 8));
      insert into public.groups (name, invite_code, created_by)
      values (p.display_name || '''s Library', code, p.id)
      returning id into gid;
      insert into public.group_members (group_id, user_id, role)
      values (gid, p.id, 'owner');
      update public.profiles
      set active_group_id = coalesce(active_group_id, gid)
      where id = p.id;
    end if;
  end loop;
end $$;

-- Assign orphan games to creator's active group
update public.games g
set group_id = p.active_group_id
from public.profiles p
where g.created_by = p.id
  and g.group_id is null
  and p.active_group_id is not null;

-- Assign orphan game nights
update public.game_nights gn
set group_id = p.active_group_id
from public.profiles p
where gn.host_id = p.id
  and gn.group_id is null
  and p.active_group_id is not null;

-- RLS
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.plays enable row level security;
alter table public.play_participants enable row level security;

-- Groups: members can view their groups
create policy "Members can view their groups"
  on public.groups for select using (
    exists (
      select 1 from public.group_members gm
      where gm.group_id = id and gm.user_id = auth.uid()
    )
  );

create policy "Authenticated users can create groups"
  on public.groups for insert with check (auth.uid() = created_by);

create policy "Owners can update their groups"
  on public.groups for update using (
    exists (
      select 1 from public.group_members gm
      where gm.group_id = id and gm.user_id = auth.uid() and gm.role = 'owner'
    )
  );

-- Group members
create policy "Members can view group membership"
  on public.group_members for select using (
    exists (
      select 1 from public.group_members gm
      where gm.group_id = group_id and gm.user_id = auth.uid()
    )
  );

create policy "Users can join groups"
  on public.group_members for insert with check (auth.uid() = user_id);

create policy "Users can leave groups"
  on public.group_members for delete using (auth.uid() = user_id);

-- Plays
create policy "Group members can view plays"
  on public.plays for select using (
    exists (
      select 1 from public.group_members gm
      where gm.group_id = plays.group_id and gm.user_id = auth.uid()
    )
  );

create policy "Group members can log plays"
  on public.plays for insert with check (
    auth.uid() = logged_by and
    exists (
      select 1 from public.group_members gm
      where gm.group_id = plays.group_id and gm.user_id = auth.uid()
    )
  );

create policy "Loggers can delete their plays"
  on public.plays for delete using (auth.uid() = logged_by);

-- Play participants
create policy "Group members can view play participants"
  on public.play_participants for select using (
    exists (
      select 1 from public.plays pl
      join public.group_members gm on gm.group_id = pl.group_id
      where pl.id = play_id and gm.user_id = auth.uid()
    )
  );

create policy "Play loggers can manage participants"
  on public.play_participants for all using (
    exists (
      select 1 from public.plays pl
      where pl.id = play_id and pl.logged_by = auth.uid()
    )
  );

-- Update games policies for group scoping
drop policy if exists "Games are viewable by everyone" on public.games;
create policy "Group members can view games"
  on public.games for select using (
    group_id is null or exists (
      select 1 from public.group_members gm
      where gm.group_id = games.group_id and gm.user_id = auth.uid()
    )
  );

drop policy if exists "Authenticated users can create games" on public.games;
create policy "Group members can create games"
  on public.games for insert with check (
    auth.uid() is not null and
    exists (
      select 1 from public.group_members gm
      where gm.group_id = games.group_id and gm.user_id = auth.uid()
    )
  );

-- Join group by invite code (security definer)
create or replace function public.join_group_by_invite(invite text)
returns uuid as $$
declare
  gid uuid;
begin
  select id into gid from public.groups where invite_code = upper(invite);
  if gid is null then
    raise exception 'Invalid invite code';
  end if;
  insert into public.group_members (group_id, user_id, role)
  values (gid, auth.uid(), 'member')
  on conflict (group_id, user_id) do nothing;
  update public.profiles set active_group_id = gid where id = auth.uid();
  return gid;
end;
$$ language plpgsql security definer;

-- Mark existing users as onboarded (new signups start fresh)
update public.profiles set onboarding_completed = true;

grant execute on function public.join_group_by_invite(text) to authenticated;

-- >>> 004_tier1_features.sql
-- BgLib Tier 1 Features Migration

-- Want to play
create table if not exists public.want_to_play (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  game_id uuid references public.games(id) on delete cascade not null,
  group_id uuid references public.groups(id) on delete cascade not null,
  created_at timestamptz default now() not null,
  unique (user_id, game_id, group_id)
);

create index if not exists want_to_play_group_idx on public.want_to_play (group_id);
create index if not exists want_to_play_game_idx on public.want_to_play (game_id);

-- Notification preferences on profiles
alter table public.profiles
  add column if not exists email_notifications boolean default true not null;

-- Loan reminder tracking
alter table public.loans
  add column if not exists reminder_sent_at timestamptz;

-- RLS for want_to_play
alter table public.want_to_play enable row level security;

create policy "Group members can view want to play"
  on public.want_to_play for select using (
    exists (
      select 1 from public.group_members gm
      where gm.group_id = want_to_play.group_id and gm.user_id = auth.uid()
    )
  );

create policy "Users can manage their want to play"
  on public.want_to_play for all using (auth.uid() = user_id);

-- Allow group members to update games in their group
drop policy if exists "Creators can update their games" on public.games;
create policy "Group members can update group games"
  on public.games for update using (
    exists (
      select 1 from public.group_members gm
      where gm.group_id = games.group_id and gm.user_id = auth.uid()
    )
  );

-- Allow group members to delete games in their group (for merge cleanup)
create policy "Group members can delete group games"
  on public.games for delete using (
    exists (
      select 1 from public.group_members gm
      where gm.group_id = games.group_id and gm.user_id = auth.uid()
    )
  );

-- >>> 005_rls_hardening.sql
-- RLS hardening: scope game nights and ownership by group membership

drop policy if exists "Game nights are viewable by everyone" on public.game_nights;
create policy "Group members can view game nights"
  on public.game_nights for select using (
    group_id is null or exists (
      select 1 from public.group_members gm
      where gm.group_id = game_nights.group_id and gm.user_id = auth.uid()
    )
  );

drop policy if exists "Ownership is viewable by everyone" on public.ownership;
create policy "Group members can view ownership"
  on public.ownership for select using (
    exists (
      select 1 from public.games g
      join public.group_members gm on gm.group_id = g.group_id
      where g.id = ownership.game_id and gm.user_id = auth.uid()
    )
    or exists (
      select 1 from public.games g
      where g.id = ownership.game_id and g.group_id is null
    )
  );

-- >>> 006_fix_group_members_rls.sql
-- Fix infinite recursion in group_members RLS policies.
-- The SELECT policy queried group_members from within group_members policies.

create or replace function public.is_group_member(check_group_id uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1
    from public.group_members
    where group_id = check_group_id
      and user_id = auth.uid()
  );
$$;

create or replace function public.is_group_owner(check_group_id uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1
    from public.group_members
    where group_id = check_group_id
      and user_id = auth.uid()
      and role = 'owner'
  );
$$;

grant execute on function public.is_group_member(uuid) to authenticated;
grant execute on function public.is_group_owner(uuid) to authenticated;

drop policy if exists "Members can view their groups" on public.groups;
create policy "Members can view their groups"
  on public.groups for select using (
    public.is_group_member(id)
  );

drop policy if exists "Owners can update their groups" on public.groups;
create policy "Owners can update their groups"
  on public.groups for update using (
    public.is_group_owner(id)
  );

drop policy if exists "Members can view group membership" on public.group_members;
create policy "Members can view group membership"
  on public.group_members for select using (
    user_id = auth.uid()
    or public.is_group_member(group_id)
  );

