#!/usr/bin/env bash
# Concatenate all SQL migrations into a single install file.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/supabase/install.sql"

{
  echo "-- BgLib: Full database install"
  echo "-- Generated by scripts/build-install-sql.sh — run once in Supabase SQL Editor"
  echo "-- After running, enable Realtime replication (see supabase/README.md)"
  echo ""
  cat "$ROOT/supabase/schema.sql"
  echo ""
  for f in "$ROOT"/supabase/migrations/*.sql; do
    echo "-- >>> $(basename "$f")"
    cat "$f"
    echo ""
  done
} > "$OUT"

echo "Wrote $OUT"
